export const homeAbout = [
  {
    id: 1,
    cover: "https://img.icons8.com/dotty/80/000000/storytelling.png",
    title: "Different Courses",
    desc: "We are providing all possible undergrad research works with an approach to catagorize the works into various courses",
    link: "/courses",
  },
  {
    id: 1,
    cover: "https://img.icons8.com/ios/80/000000/search.png",
    title: "Get an insight",
    desc: "Our collective approach of storing and displaying all the undergrad thesis works will help the students getting a clear insight",
    link: "/documents",
  },
  {
    id: 1,
    cover: "https://img.icons8.com/ios/80/000000/teacher.png",
    title: "Learn with Expert",
    desc: "Our platform offering all the available research works along with the name and details of our corresponding supervisor",
    link: "/team",
  },
];
export const awrapper = [
  {
    cover:
      "https://img.icons8.com/external-yogi-aprelliyanto-basic-outline-yogi-aprelliyanto/80/ffffff/external-graduation-education-yogi-aprelliyanto-basic-outline-yogi-aprelliyanto.png",
    data: "2,000+",
    title: "SUCCESS STORIES",
  },

  {
    cover: "https://img.icons8.com/ios/80/ffffff/athlete.png",
    data: "150",
    title: "TRUSTED TUTORS",
  },
  // {
  //   cover: "https://img.icons8.com/external-outline-icons-maxicons/80/ffffff/external-calender-insurance-outline-outline-icons-maxicons.png",
  //   data: "1,000",
  //   title: "SCHEDULES",
  // },
  {
    cover: "https://img.icons8.com/ios/80/ffffff/macbook-idea--v3.png",
    data: "20+",
    title: "COURSES",
  },
];
export const online = [
  {
    cover: "./images/courses/online/ml.png",
    hoverCover: "./images/courses/online/ml1.png",
    courseName: "Machine Learning",
    course: "15",
  },
  {
    cover: "./images/courses/online/bio.png",
    hoverCover: "./images/courses/online/bio1.png",
    courseName: "Bioinformatics",
    course: "2",
  },
  {
    cover: "./images/courses/online/o3.png",
    hoverCover: "./images/courses/online/o3.1.png",
    courseName: "Data Mining",
    course: "2",
  },
  {
    cover: "./images/courses/online/o4.png",
    hoverCover: "./images/courses/online/o4.1.png",
    courseName: "Digital Image Processing",
    course: "11",
  },
  {
    cover: "./images/courses/online/o5.png",
    hoverCover: "./images/courses/online/o5.1.png",
    courseName: "Software Engineering",
    course: "3",
  },
  {
    cover: "./images/courses/online/o6.png",
    hoverCover: "./images/courses/online/o6.1.png",
    courseName: "Green Technology",
    course: "2",
  },
  {
    cover: "./images/courses/online/com.png",
    hoverCover: "./images/courses/online/comeng.png",
    courseName: "Communication Engineering",
    course: "4",
  },
  {
    cover: "./images/courses/online/network.png",
    hoverCover: "./images/courses/online/network1.png",
    courseName: "Networking",
    course: "2",
  },
  {
    cover: "./images/courses/online/graphic.png",
    hoverCover: "./images/courses/online/graphic1.png",
    courseName: "Graphic Design",
    course: "0",
  },
  {
    cover: "./images/courses/online/robot.png",
    hoverCover: "./images/courses/online/robot1.png",
    courseName: "Artificial Intelligence",
    course: "1",
  },
  {
    cover: "./images/courses/online/net.png",
    hoverCover: "./images/courses/online/net2.png",
    courseName: "Cyber Security",
    course: "3",
  },
  {
    cover: "./images/courses/online/o12.png",
    hoverCover: "./images/courses/online/o12.1.png",
    courseName: "Web Development",
    course: "0",
  },
];
export const team = [
  {
    cover: "./images/team/ashfak_sir.jpg",
    name: "Dr. A.H.M. Ashfak Habib",
    work: "Head & Professor",
    number: "88-031-714920~2, Ext. 2327",
    email: "ashfak@cuet.ac.bd",
  },
  {
    cover: "./images/team/kaushik_sir.jpg",
    name: "Dr. Kaushik Deb",
    work: "Professor",
    number: "01914745508",
    email: "debkaushik99@cuet.ac.bd",
  },
  {
    cover: "./images/team/ibrahim_sir.jpg",
    name: "Dr. Muhammad Ibrahim Khan",
    work: "Professor",
    number: "",
    email: "",
  },
  {
    cover: "./images/team/moshiul_sir.jpg",
    name: "Dr. Mohammed Moshiul Hoque",
    work: "Professor",
    number: "88-01716-133019",
    email: "moshiul_240@cuet.ac.bd",
  },
  {
    cover: "./images/team/arefin_sir.jpg",
    name: "Prof. Dr. Mohammad Shamsul Arefin",
    work: "Professor",
    number: "01716-890204",
    email: "sarefin@cuet.ac.bd",
  },
  {
    cover: "./images/team/asad_sir.jpg",
    name: "Dr. Asaduzzaman",
    work: "Professor",
    number: "01938534828",
    email: "asad@cuet.ac.bd",
  },
  {
    cover: "./images/team/mokammel_sir.jpg",
    name: "Dr. Md. Mokammel Haque",
    work: "Professor",
    number: "+880-31714920-22 (ext. 2307)",
    email: "mokammel@cuet.ac.bd",
  },
  {
    cover: "./images/team/kamal_sir.jpg",
    name: "Muhammad Kamal Hossen",
    work: "Associate Professor",
    number: "+880-1816-012649, +880-1745-723385",
    email: "mkhossen@cuet.ac.bd",
  },
  {
    cover: "./images/team/obaidur_sir.jpg",
    name: "Obaidur Rahman",
    work: "Associate Professor",
    number: "01731-808646, 01970-808646, 031-714920-22",
    email: "obaidur_91@cuet.ac.bd",
  },
  {
    cover: "./images/team/saki_sir.jpg",
    name: "Mir Md. Saki Kowsar",
    work: "Assistant Professor",
    number: "",
    email: "sakikowsar@cuet.ac.bd",
  },
  {
    cover: "./images/team/ikbal_sir.jpg",
    name: "Dr. Md. Iqbal Hasan Sarker",
    work: "Associate Professor",
    number: " 01913018009",
    email: "iqbal@cuet.ac.bd",
  },
  {
    cover: "./images/team/ibrahim_sir.jpg",
    name: "Dr. Mahfuzulhoq Chowdhury",
    work: "Associate Professor",
    number: "",
    email: "mahfuz@cuet.ac.bd",
  },
  {
    cover: "./images/team/mukta_miss.jpg",
    name: "Rahma Bintey Mufiz Mukta",
    work: "Assistant Professor",
    number: "+8801991956205",
    email: "tahmina_iict@cuet.ac.bd",
  },
  {
    cover: "./images/team/tahmina_miss.jpg",
    name: "Tahmina Khanam",
    work: "Assistant Professor",
    number: "+8801791981040, +61426834319",
    email: "rahmamukta@cuet.ac.bd",
  },
  {
    cover: "./images/team/lamia_miss.jpg",
    name: "Lamia Alam",
    work: "Assistant Professor",
    number: "",
    email: "lamia_alam@cuet.ac.bd",
  },
  {
    cover: "./images/team/animesh_sir.jpg",
    name: "Animesh Chandra Roy",
    work: "Assistant Professor",
    number: "+8801738503339",
    email: "animesh_roy@cuet.ac.bd",
  },
  {
    cover: "./images/team/sabir_sir.jpg",
    name: "Md. Sabir Hossain",
    work: "Assistant Professor",
    number: "+8801737143868, +8801882826575",
    email: "sabir.cse@cuet.ac.bd",
  },
  {
    cover: "./images/team/forhad_sir.jpg",
    name: "Md. Shafiul Alam Forhad",
    work: "Assistant Professor",
    number: "01746844971",
    email: "forhad0904063@cuet.ac.bd",
  },
  {
    cover: "./images/team/tista_miss.jpg",
    name: "Sharmistha Chanda Tista",
    work: "Assistant Professor",
    number: "",
    email: "tista_chanda@cuet.ac.bd",
  },
  {
    cover: "./images/team/ibrahim_sir.jpg",
    name: "Md. Mynul Hasan",
    work: "Assistant Professor",
    number: "+8801727816073",
    email: "mynul@cuet.ac.bd",
  },
  {
    cover: "./images/team/annesha_miss.jpg",
    name: "Annesha Das",
    work: "Assistant Professor",
    number: "",
    email: "annesha@cuet.ac.bd",
  },
  {
    cover: "./images/team/ashim_sir.jpg",
    name: "Ashim Dey",
    work: "Assistant Professor",
    number: "+8801738638164",
    email: "ashim@cuet.ac.bd",
  },
  {
    cover: "./images/team/billal_sir.jpg",
    name: "Md. Billal Hossain",
    work: "Assistant Professor",
    number: "+8801845188399, +8801521483247",
    email: "mhbillal@cuet.ac.bd",
  },
  {
    cover: "./images/team/rijvi_sir.jpg",
    name: "Md. Atiqul Islam Rizvi",
    work: "Assistant Professor",
    number: "+8801780301785, +8801521414137",
    email: "mhbillal@cuet.ac.bd",
  },
  {
    cover: "./images/team/sabiha_miss.jpg",
    name: "Sabiha Anan",
    work: "Assistant Professor",
    number: "+8801680123824",
    email: "mhbillal@cuet.ac.bd",
  },
  {
    cover: "./images/team/billal_sir.jpg",
    name: "Md. Billal Hossain",
    work: "Assistant Professor",
    number: "+8801845188399, +8801521483247",
    email: "sabiha.anan@cuet.ac.bd",
  },
  {
    cover: "./images/team/rashad_sir.jpg",
    name: "Md. Rashadur Rahman",
    work: "Lecturer",
    number: "+8801534770467",
    email: "rashadur@cuet.ac.bd",
  },
  {
    cover: "./images/team/hm_sir.jpg",
    name: "Hasan Murad",
    work: "Lecturer",
    number: "",
    email: "hasanmurad@cuet.ac.bd",
  },
  {
    cover: "./images/team/avishek_sir.jpg",
    name: "Avishek Das",
    work: "Lecturer",
    number: "+8801799730137",
    email: "avishek@cuet.ac.bd",
  },
  {
    cover: "./images/team/moumita_miss.jpg",
    name: "Moumita Sen Sarma",
    work: "Lecturer",
    number: "01819627559",
    email: "moumita@cuet.ac.bd",
  },
  {
    cover: "./images/team/sakib_sir.jpg",
    name: "Saadman Sakib",
    work: "Lecturer",
    number: "01521334417",
    email: " saadman@cuet.ac.bd",
  },
  {
    cover: "./images/team/aonty_miss.jpg",
    name: "Shuhena Salam Aonty",
    work: "Lecturer",
    number: " 01954254036",
    email: "shuhena@cuet.ac.bd",
  },
];
export const price = [
  {
    name: "BASIC PLAN",
    price: "49K",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
  },
  {
    name: "BEGINNER PLAN",
    price: "79K",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
  },
  {
    name: "PREMIUM PLAN",
    price: "109k",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
  },
  {
    name: "ULTIMATE PLAN",
    price: "149K",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
  },
];
export const faq = [
  {
    title: "How to Enroll This Online Courses?",
    desc: "This is the first item's accordion body. It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
  {
    title: "Where It is hidden by default, until the collapse?",
    desc: "It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
  {
    title: "How It is hidden by default, until the collapse?",
    desc: "It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
  {
    title: "How to Enroll This Online Courses?",
    desc: "This is the first item's accordion body. It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
  {
    title: "Where It is hidden by default, until the collapse?",
    desc: "It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
  {
    title: "How It is hidden by default, until the collapse?",
    desc: "It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
];
export const blog = [
  {
    id: 1,
    type: "admin",
    date: "JAN. 18, 2021",
    com: "3 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b1.webp",
  },
  {
    id: 2,
    type: "admin",
    date: "API. 25, 2022",
    com: "5 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b2.webp",
  },
  {
    id: 3,
    type: "user",
    date: "MAY. 15, 2022",
    com: "10 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b3.webp",
  },
  {
    id: 4,
    type: "admin",
    date: "JAN. 02, 2022",
    com: "3 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b4.webp",
  },
  {
    id: 5,
    type: "admin",
    date: "DEC. 14, 2022",
    com: "3 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b5.webp",
  },
  {
    id: 6,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
];